import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    borderRadius: 20,
    padding: 20,
    minHeight: 260,
    alignSelf: "center",
    justifyContent: "flex-start",
    borderWidth: 0.45,
    borderColor: "#055d29ff",
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  iconWrapper: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 24,
    padding: 8,
  },
  badge: {
    backgroundColor: "#FFA726",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "white",
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: "white",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "white",
    opacity: 0.9,
    marginBottom: 16,
  },
  rewardsRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 12,
    marginTop: 16,
  },
  rewardPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  rewardText: {
    marginLeft: 6,
    fontSize: 13,
    fontWeight: "500",
    color: "white",
  },
  swipeHints: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "90%",
    marginTop: 12,
    paddingHorizontal: 8,
  },
  hintLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  hintRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  hintText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#6B7280",
  },
  lockedCard: {
    width: "90%",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 24,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  lockedTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
    marginTop: 16,
    marginBottom: 6,
  },
  lockedSubtitle: {
    fontSize: 14,
    color: "#475569",
    textAlign: "center",
  },
  limitMessage: {
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(37, 99, 235, 0.1)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  limitMessageText: {
    fontSize: 13,
    color: "#2563EB",
    flex: 1,
  },
});
